apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-data
  namespace: usage-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
